openapi: 3.0.0

info:
  title: Filmhub API
  description: ...
  version: 0.0.1

servers:
  - url: https://app.filmhub.com/api/v1
    description: Production API server
  - url: http://localhost:3000
    description: Development local server

paths:
  /animals/{animalId}:
    get:
      summary: Returns single animal
      operationId: getAnimal
      parameters:
      - name: animalId
        in: path
        description: ID of the animal
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Animal"
              examples:
                piglet:
                  summary: Example of animal
                  value:
                    id: 111
                    name: Example animal
                    kind: Piglet
  /animals:
    get:
      summary: Returns animals list
      operationId: getAnimals
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Animal"

components:
  schemas:
    Animal:
      type: object
      properties:
        id:
          type: integer
          x-faker: random.number
        name:
          type: string
          x-faker: name.firstName
        kind:
          type: string
          x-faker: lorem.word